---


- apt_key: id=D88E42B4 url=https://artifacts.elastic.co/GPG-KEY-elasticsearch

- apt_repository: repo="deb https://artifacts.elastic.co/packages/5.x/apt stable main"

- apt: name=metricbeat


- name: update the configuration file by templating
  template: src=metricbeat.yml.j2 dest={{ METRICBEAT_INSTALL_DIR }}/metricbeat.yml owner={{ METRICBEAT_USER}} group={{ METRICBEAT_GROUP }}
  notify:
    - restart metricbeat

